from setuptools import setup

setup(name='UnittestOne',
      version='0.1.0',
      description='An Assertion Framework for API testing',
      author='Leah Klearman',
      author_email='lklrmn at gmail dot com',
      url='https://github.com/klrmn/Unittest-One',
      classifiers=['Development Status :: 3 - Alpha',
                  'Intended Audience :: Developers',
                  'License :: OSI Approved :: The MIT License (MIT)',
                  'Operating System :: POSIX',
                  'Operating System :: Microsoft :: Windows',
                  'Operating System :: MacOS :: MacOS X',
                  'Topic :: Software Development :: Testing',
                  'Topic :: Software Development :: Libraries',
                  'Programming Language :: Python'],
      py_modules=['unittestone'],
      install_requires=['unittestzero', 'testmania'],
)
